# Theme configuration
theme: linkhub-jekyll-theme

# Site information
name: Harry Fücks Comedy
description: >- # this means to ignore newlines until "baseurl:"
  Join Harry Fücks, the ginger-bearded, stand-up comedian, as he navigates life over 50+, singledom, fatherhood , and tech chaos — because laughter is the only way out.
url: https://harryf.ckscomedy.com
locale: en_GB

# Social media
twitter:
  username: harryf

# Favicon configuration
favicon:
  path: /assets/images/favicon.png
  type: png

# Logo configuration
logo: /assets/images/harryfucks.png

# Open Graph image configuration
image:
  path: /assets/images/harryfucks.png
  type: png
  height: 100
  width: 100
  alt: Harry Fücks Logo

# Verified Badge Configuration
badge:
  enable: true
  icon: ri:verified-badge-fill
  color: '#1da1f2'

# Analytics and Marketing configurations
# Google Analytics 4
ga4:
  enable: true
  measurement_id: G-7M07W8HVGF

# Mailchimp
mailchimp:
  enable: false
  form_url: https://chimpstatic.com/mcjs-connected/js/users/1f8722669657924e883f3ea8a/f5cf3ffe7db8d421109f8151f.js

# Default layout configuration
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Collections configuration
collections_dir: pages
collections:
  upcoming_shows:
    sort_by: order
  shows:
    output: true
    sort_by: order
  things:
    output: true
    sort_by: order
  booking:
    output: true

# Files and directories to exclude from processing
exclude: 
  - README.md
  - Gemfile.lock
  - .jekyll-cache/
  - .github/
  - CHANGELOG.md
  - Gemfile
  - LICENSE.txt
  - funding.yml
  - linkhub-jekyll-theme.gemspec
