backend:
  name: github
  repo: harryf/harryfucks # Your GitHub username and repository
  branch: main
  auth_scope: public_repo

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }