backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "upcoming_shows"
    label: "Upcoming Shows"
    folder: "_upcoming_shows"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Ticket URL", name: "ticket_url", widget: "string" }
      - { label: "Show Info", name: "show_info", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
